apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: example-blue-green
  namespace: default
spec:
  replicas: 3
  strategy:
    blueGreen:
      activeService: example-active
      previewService: example-preview
      autoPromotionEnabled: false
  selector:
    matchLabels:
      app: example-app
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
        - name: app
          image: nginx:1.21.6 # Replace with your application image
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: example-active
  namespace: default
spec:
  selector:
    app: example-app
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: example-preview
  namespace: default
spec:
  selector:
    app: example-app
  ports:
    - port: 80
      targetPort: 80